Update nix-vm-test to support latest change in nixpkgs
Fixes broken tests due to recent changes in nixpkgs affecting VM tests:

```
error: evaluation aborted with the following error message: 'lib.customisation.callPackageWith: Function called without required argument "buildPythonApplication" at /nix/store/24b29jfv23y9mh5ib7a5yljcgm0n65kw-source/nixos/lib/test-driver/default.nix:4'
```

See https://github.com/numtide/nix-vm-test/pull/147